# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
assistant_id: chatbot-nutricional

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt

# https://rasa.com/docs/rasa/tuning-your-model
# https://rasa.com/docs/reference/config/components/nlu-components
pipeline:
  # https://spacy.io/models/pt#pt_core_news_md
  # https://github.com/RasaHQ/rasa/blob/3.6.x/rasa/nlu/utils/spacy_utils.py
  # 1. SpacyNLP: Carrega o modelo spaCy pre-treinado para portugues.
  - name: SpacyNLP
    model: "pt_core_news_md"
    case_sensitive: false
  # https://github.com/RasaHQ/rasa/blob/3.6.x/rasa/nlu/tokenizers/spacy_tokenizer.py
  # 2. SpacyTokenizer: Usa as regras do spaCy para dividir o texto em tokens.  
  - name: SpacyTokenizer
  # https://github.com/RasaHQ/rasa/blob/3.6.x/rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py
  # 3. SpacyFeaturizer: Cria representacoes vetoriais densas para os tokens.
  - name: SpacyFeaturizer
    pooling: "mean"
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
