FROM python:3.10.14-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc git curl libffi-dev libpq-dev libssl-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir rasa-sdk pandas

COPY . /app

EXPOSE 5055

CMD ["rasa", "run", "actions", "--port", "5055", "--debug"]
